CREATE TABLE IF NOT EXISTS USERS(
    id UUID,
    username VARCHAR(25) NOT NULL UNIQUE,
    password VARCHAR(72) NOT NULL,
    email VARCHAR(25) NOT NULL,
    phone VARCHAR(15),
    CONSTRAINT USERS_PK PRIMARY KEY (id)
);