CREATE TABLE IF NOT EXISTS USERS_ROLES(
    user_id UUID NOT NULL,
    role_id UUID NOT NULL,
    CONSTRAINT USERS_ROLES_PK PRIMARY KEY (user_id, role_id),
    CONSTRAINT USERS_ROLES_USERS_FK FOREIGN KEY (user_id) REFERENCES USERS(id),
    CONSTRAINT USERS_ROLES_ROLES_FK FOREIGN KEY (role_id) REFERENCES ROLES(id)
);