spring.application.name=Librus
server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5432/librus
spring.datasource.username=librus
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
logging.level.org.springframework.web=debug
logging.level.org.springframework.security=debug
logging.level.org.springframework.data=debug