spring.application.name=Librus
server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5432/librus
spring.datasource.username=librus
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:database/migrations

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
logging.level.org.springframework.web=debug
logging.level.org.springframework.security=debug
logging.level.org.springframework.data=debug

jwt.issuer=librus
jwt.audience=librus
jwt.access-token.expiration=300000
jwt.refresh-token.expiration=604800000
jwt.secret=KC7Susfk7y3pAB3o5kUjhRfh4pVuKvwSn5ZT1EhJv34=